### ISSUE TITLE
VPN or QUIC Proxy?

### ISSUE THREAD

**Issue by huitema** [DavidSchinazi/masque-drafts#1]
I would like to support a QUIC proxy because it is much easier to deploy, requires just one port.

**Comment by DavidSchinazi** [comment]
Why not both? I think we can have MASQUE be a framework where both proxy and VPN can be negotiated and co-exist.

**Comment by huitema** [comment]
As long as the client does not actually expect a VPN, that's fine with me. But consider my little server on AWS. It has access to exactly one IPv4 address and one IPv6 address, so it cannot possibly act as an IP level VPN. But it can act as a proxy.

**Comment by DavidSchinazi** [comment]
Agreed, the server needs to clearly advertise which services it offers.

That said, you can run an IP-level VPN with a single IP as long as you use NAT. This is one of the rare use cases where NAT actually helps the client by providing IP obfuscation.

**Comment by huitema** [comment]
You could try to run a NAT, but I would rather not be forced to implement that. Lots of complexity, attack surface, etc.

**Comment by DavidSchinazi** [comment]
Fair enough. I just want to keep VPN as a potential use-case, but agree that working on proxying is higher priority.

**Comment by DavidSchinazi** [comment]
This is now covered by https://github.com/tfpauly/quic-proxy
