### ISSUE TITLE
Don't use .well-known

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/masque-drafts#14]
You don't need to do that.  Configuring a URL seems as likely to work as a domain name and it provides additional deployment flexibility for the application.

**Comment by DavidSchinazi** [comment]
That's a good point! I think we'll want to keep #15 in mind when making this change but if we allow any URL and require a `Sec-` header we're probably in better shape?

**Comment by DavidSchinazi** [comment]
This ended up being covered by the [Client Configuration section of RFC 9298](https://www.rfc-editor.org/rfc/rfc9298#name-client-configuration)
