### ISSUE TITLE
What is the MASQUE POST body content-type

### ISSUE THREAD

**Issue by LPardue** [DavidSchinazi/masque-drafts#16]
The client part of negotiation requires a client to send a POST request with a sequence of TLVs. What is the content-type of that payload body?

**Comment by DavidSchinazi** [comment]
That's a good point, we probably will want to define and register a new Media Type with [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml).

**Comment by DavidSchinazi** [comment]
Overcome by events
