### ISSUE TITLE
CONNECT-UDP request body

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/masque-drafts#22]
>    A payload within a CONNECT-UDP request message has no defined semantics; a CONNECT-UDP request with a non-empty payload is malformed.

I think that this text is out of sync with the rest of the doc.  The payload is used to carry UDP packets, even when you use DATAGRAM frames.

**Comment by DavidSchinazi** [comment]
I think this is just a question of semantics. CONNECT takes over the stream, and therefore the contents of that stream are not considered to be the payload of the HTTP response.

From [RFC 7231 s4.3.6](https://tools.ietf.org/html/rfc7231#section-4.3.6):
>   A payload within a CONNECT request message has no defined semantics;
>   sending a payload body on a CONNECT request might cause some existing
>   implementations to reject the request.

**Comment by DavidSchinazi** [comment]
This issue has been moved to the [official WG repo](https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/issues/2)
