### ISSUE TITLE
Flow duration

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/masque-drafts#24]
The CONNECT-UDP proxy has to act a little like a NAT when it forwards UDP.  It has to assign a source IP and port.  Those probably need to be dedicated to the flow for its lifetime.  However, UDP lacks the clear signals of TCP about connection termination, so we need a clear definition of what lifetime is.  

It is perhaps reasonable to tie the lifetime of the allocation to the existence of the stream, but then the connection from the client might drop mid-flow; how long does the proxy need to avoid reusing that address?

The proxy might also decide that idleness is cause for dropping bindings.  The client needs to know this because it will need to make new tunnels to continue communication if it goes idle for too long.

**Comment by DavidSchinazi** [comment]
The intent was to have the lifetime of the UDP socket be tied to the existence of the CONNECT-UDP stream. But I agree that we should add text indicating that a server MAY want to garbage collect these after idle periods, and in that case it MUST close the corresponding stream to inform the client.

**Comment by DavidSchinazi** [comment]
This issue has been moved to the [official WG repo](https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/issues/4)
