### ISSUE TITLE
Security issue: abusing third parties

### ISSUE THREAD

**Issue by huitema** [DavidSchinazi/masque-drafts#3]
One of the security issues with Masque proxies is whether they can be used to attack third parties. The attacking client would connect to the Masque server, and push packets towards a third party with a goal of attacking that party. It could be part of a "targeted" attack, sending specially crafted packets to activate a bug and crash or pwn the target. Or it could be a volumetric attack, with the client sending large number of transactions to try DOS the target.

Such abuses can cause reputation issues for the proxy, eventually landing the proxy's IP address in some kind of blacklist. It seems that Masque implementations should recognize the issue and do something about it.

The first line of defense is of course to only serve authorized clients, but that's not a perfect defense. Attackers could somehow hack an authorized client and get its credentials. Or, they could subscribe to the service with a throw-away identity.

The second line of defense, used for example in TURN, is to restrict what clients can do. This amounts to building some kind of basic firewall in the Masque proxy, with rules like inspecting packets or limiting packet rates.

I wonder whether we should add text to that effect in the specification?

**Comment by DavidSchinazi** [comment]
This makes sense to me. Perhaps we can go into more detail in a new subsection of Security Considerations?

**Comment by eighthave** [comment]
I agree these are all valid issues, but it seems to me that they would be handled outside of MASQUE itself.  It seems to me that MASQUE should serve as the glue between a QUIC server and an HTTP CONNECT proxy daemon.  A standard HTTP CONNECT proxy implementation should cover connecting to an auth backend as well as restrictions on what is allowed to be proxied.  For example, _privoxy_ provides _enforce-blocks_: https://www.privoxy.org/3.0.26/user-manual/config.html#ENFORCE-BLOCKS

MASQUE might need to specify how these blocks/limits/etc are communicated to the client, e.g. if the HTTP CONNECT methods don't cover everything.  My gut feeling is that HTTP status codes will probably be enough.

**Comment by DavidSchinazi** [comment]
I agree that these issues don't necessarily need to be handled in the MASQUE protocol text, but mentioning it in the Security Considerations section can't hurt

**Comment by DavidSchinazi** [comment]
This ended up being covered in the [Security Considerations of RFC 9298](https://www.rfc-editor.org/rfc/rfc9298#name-security-considerations)
