### ISSUE TITLE
Pluggable Transports - any relationship?

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [DavidSchinazi/masque-drafts#4]
Our community, working with the [PEARG](https://irtf.org/pearg) folks in IRTF, submitted an Internet Draft of our on-going work on network traffic obfuscation called "Pluggable Transports".  It's [HERE](https://www.ietf.org/id/draft-oliver-pluggable-transports-00.txt). I'm one of the authors.  This work, begun at the Tor Project with later cooperation from organizations serving the Human Rights and Internet Freedom areas, has been focused on TCP. We'd be interested to understand if there is a relationship between this work and your work on MASQUE, and/or if there is possibility to cooperate.

**Comment by DavidSchinazi** [comment]
I would love to cooperate on this! The main goal of MASQUE is to provide a general-purpose mechanism to multiplex transports with HTTP/3 connections in the way that is hard to distinguish by unauthenticated third-parties. I definitely see Tor pluggable transports as a compelling use-case for MASQUE.

What would it take to create a MASQUE pluggable transport?

Note that we haven't yet built an implementation of MASQUE, mainly because the project contributors are focused on QUIC right now, but as QUIC nears standardization I think there'll be energy to build MASQUE and see if it works in the real world.

**Comment by huitema** [comment]
On 10/21/2019 1:04 PM, David Schinazi wrote:
>
> I would love to cooperate on this! The main goal of MASQUE is to
> provide a general-purpose mechanism to multiplex transports with
> HTTP/3 connections in the way that is hard to distinguish by
> unauthenticated third-parties. I definitely see Tor pluggable
> transports as a compelling use-case for MASQUE.
>
> What would it take to create a MASQUE pluggable transport?
>
> Note that we haven't yet built an implementation of MASQUE, mainly
> because the project contributors are focused on QUIC right now, but as
> QUIC nears standardization I think there'll be energy to build MASQUE
> and see if it works in the real world.
>
I am actually busy writing an implementation of a Quic proxy based on
Masque and Picoquic. I am actually writing a protocol implementation
that can work either on top of H3 (or H09), sending the protocol
commands over post, or directly on top of Quic, reserving an ALPN for
Quic in Quic. It is basically the same code, with a bit of glue. The
difference in overhead is minimal.

For a proxy scenario or an onion scenario, the overhead that matters is
the recursive encapsulation of Quic packets in datagram frames. The
native scenario can assume that all datagrams contain forwarded Quic
packets, but the HTTP scenarios cannot -- there needs to be at least one
byte to differentiate that from other usages of Quic datagrams. That one
byte probably matters less for the onion scenario than the general
stealth of appearing like H3 traffic.

The good part of writing implementations is that it forces thinking hard
about protocol issues. How do we manage header compression in the
datagram frame payload so as to minimize the additional overhead of each
forwarding hop? How do we deal with inbound routing by DCID while
solving synchronization issues and potential security issues? If we want
to support inbound connections, do we need an explicit authentication
scheme to match SNI and relays? Can we use self-certifying names like
.onion?

More about all that soon...

-- Christian Huitema

**Comment by m4mb01t4l14n0** [comment]
@DavidSchinazi will you be at IETF106 in Singapore?  Perhaps we can discuss implementation possibilities (and practicalities).

**Comment by DavidSchinazi** [comment]
Hi @m4mb01t4l14n0 ! Yes @huitema and I will be in Singapore. We were thinking of hanging out at the QUIC table at the hackathon over the weekend. Will you be there for that?

**Comment by m4mb01t4l14n0** [comment]
@DavidSchinazi YES, I will be there for hackathon, arriving Friday (though I'm staying at a non-conference hotel for the first 3 nights).  I'll look you up (I might be doing a hackathon session myself - have to verify that).

**Comment by DavidSchinazi** [comment]
@m4mb01t4l14n0 sounds good! Feel free to [email me](https://tools.ietf.org/html/draft-schinazi-masque-01#page-13) when you're there!

**Comment by DavidSchinazi** [comment]
Overcome by events, this is now discussed on [draft-ietf-httpbis-unprompted-auth](https://datatracker.ietf.org/doc/draft-ietf-httpbis-unprompted-auth/)
