### ISSUE TITLE
MASQUE request processing MUST run in constant time

### ISSUE THREAD

**Issue by chris-wood** [DavidSchinazi/masque-drafts#5]
Imagine adversary Adv knows the username of a MASQUE user, and observes a connection to a supposed MASQUE server. Adv could determine whether or not the user initiated a MASQUE connection as follows:

1. Connect to the server and send a MASQUE request with the correct username and bogus signature. Measure the time to response as T1.
2. Connect to the server and send a MASQUE request with a bogus username and signature. Measure the time to response as T2.

If T1 >> T2, this suggests that the username is valid for the given MASQUE server. 

MASQUE servers should process (username, signature) request tuples in constant time so as to not leak this type of information.

**Comment by DavidSchinazi** [comment]
Agreed. I'll add a MUST to require that verifying the username and signature is a constant-time operation.

**Comment by klzgrad** [comment]
Related: To satisfy the requirement of server invisibility https://www.ietf.org/archive/id/draft-schinazi-masque-obfuscation-04.html#name-invisibility-of-the-server, a request without authentication must also use the same constant time to not expose the server.

**Comment by DavidSchinazi** [comment]
This is now covered by https://github.com/httpwg/http-extensions/issues/2437 and is being fixed by https://github.com/httpwg/http-extensions/pull/2466
