### ISSUE TITLE
corp/organization VPN use case

### ISSUE THREAD

**Issue by eighthave** [DavidSchinazi/masque-drafts#7]
The abstract seems to unnecessarily restrict the use case for MASQUE.  I can see a very clear use case for corporations/governments/organizations: VPNs are being blocked and tracked more and more frequently.  Travelling employees need VPNs to work.  Such groups would then want to run MASQUE on their own infrastructure to obfuscate their own VPN traffic.  Many OpenVPN providers offer obfs4 tunneling, for example.  If the network that the travelling employee has access to blocks all OpenVPN traffic, then MASQUE to their own infrastructure would help.

@m4mb01t4l14n0 @uniqx

**Comment by DavidSchinazi** [comment]
Which abstract are you referring to? The [MASQUE](https://davidschinazi.github.io/masque-drafts/draft-schinazi-masque.html) one or the [MASQUE Obfuscation](https://davidschinazi.github.io/masque-drafts/draft-schinazi-masque-obfuscation.html) one?

**Comment by eighthave** [comment]
oops, sorry I was responding to this old draft: https://tools.ietf.org/html/draft-schinazi-masque-00
