### ISSUE TITLE
explicitly state that MASQUE's HTTP CONNECT should reply as if it wasn't there

### ISSUE THREAD

**Issue by eighthave** [DavidSchinazi/masque-drafts#8]
From 3. Overview of the Mechanism, I understand the goal as making sure that the HTTP CONNECT responses do not divulge whether MASQUE is present or not.   I think this needs to be spelled out a bit more, since HTTP CONNECT can be used without any auth.  This would then make it clear that the MASQUE server should respond to HTTP CONNECT requests without auth the same as it would for failed auth.  Or maybe its better to say that the MASQUE server only considers HTTP CONNECT requests with MASQUE pseudo-header, and everything else is entirely ignored.

@uniqx @m4mb01t4l14n0

**Comment by DavidSchinazi** [comment]
I think you may have read an outdated copy, does the latest [overview section](https://davidschinazi.github.io/masque-drafts/draft-schinazi-masque-obfuscation.html#name-overview-of-the-mechanism) handle this better?

**Comment by eighthave** [comment]
Yes, sorry.  The current document in this GitHub repo is clear on this.
